version: '3.8'

services:
  mongo-express:
    image: mongo-express:{{MONGO_EXPRESS_VERSION}}
    container_name: {{APP_NAME}}_mongo_express
    restart: unless-stopped
    ports:
      - "{{MONGO_EXPRESS_PORT}}:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://{{MONGODB_USERNAME}}:{{MONGODB_PASSWORD}}@{{MONGODB_HOST}}:{{MONGODB_PORT}}/
      ME_CONFIG_BASICAUTH_USERNAME: {{MONGO_EXPRESS_USERNAME}}
      ME_CONFIG_BASICAUTH_PASSWORD: {{MONGO_EXPRESS_PASSWORD}}
    networks:
      - {{APP_NAME}}_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  {{APP_NAME}}_network:
    driver: bridge

