#!/bin/bash

# 测试路径前缀匹配功能
echo "🛣️ 测试路径前缀匹配功能"
echo "================================"

echo "📋 功能说明："
echo "  ✅ 静态站点支持路径前缀匹配"
echo "  ✅ PHP站点支持路径前缀匹配"
echo "  ✅ 代理转发支持路径前缀匹配"
echo "  ✅ 负载均衡支持路径前缀匹配"

echo ""
echo "🔧 配置示例："
echo ""
echo "1. 静态站点配置："
echo "   {"
echo "     \"domain\": \"example.com\","
echo "     \"root\": \"/var/www/html\","
echo "     \"path_prefixes\": [\"/api/v1/\", \"/api/v2/\", \"/admin/\"],"
echo "     \"path_exact\": false"
echo "   }"

echo ""
echo "2. PHP站点配置（多组路径前缀规则）："
echo "   {"
echo "     \"domain\": \"php.example.com\","
echo "     \"root\": \"/var/www/php\","
echo "     \"fcgi_addr\": \"127.0.0.1:9000\","
echo "     \"path_prefix_rules\": ["
echo "       {"
echo "         \"name\": \"API v1 规则\","
echo "         \"enabled\": true,"
echo "         \"prefixes\": [\"/api/v1/\", \"/api/v1/users/\"],"
echo "         \"exact\": false,"
echo "         \"backends\": ["
echo "           {\"host\": \"api-v1-server-1.example.com\", \"port\": 8080, \"weight\": 2},"
echo "           {\"host\": \"api-v1-server-2.example.com\", \"port\": 8080, \"weight\": 1}"
echo "         ],"
echo "         \"load_balancer_algorithm\": \"weighted_round_robin\""
echo "       },"
echo "       {"
echo "         \"name\": \"API v2 规则\","
echo "         \"enabled\": true,"
echo "         \"prefixes\": [\"/api/v2/\", \"/api/v2/users/\"],"
echo "         \"exact\": false,"
echo "         \"backends\": ["
echo "           {\"host\": \"api-v2-server-1.example.com\", \"port\": 8080, \"weight\": 1},"
echo "           {\"host\": \"api-v2-server-2.example.com\", \"port\": 8080, \"weight\": 1}"
echo "         ],"
echo "         \"load_balancer_algorithm\": \"round_robin\""
echo "       },"
echo "       {"
echo "         \"name\": \"管理后台规则\","
echo "         \"enabled\": true,"
echo "         \"prefixes\": [\"/admin/\", \"/admin/login\"],"
echo "         \"exact\": false,"
echo "         \"backends\": ["
echo "           {\"host\": \"admin-server-1.example.com\", \"port\": 8080, \"weight\": 1}"
echo "         ],"
echo "         \"load_balancer_algorithm\": \"round_robin\""
echo "       }"
echo "     ]"
echo "   }"

echo ""
echo "3. 代理转发配置："
echo "   {"
echo "     \"domain\": \"proxy.example.com\","
echo "     \"backends\": ["
echo "       {\"host\": \"backend1.example.com\", \"port\": 8080},"
echo "       {\"host\": \"backend2.example.com\", \"port\": 8080}"
echo "     ],"
echo "     \"path_prefixes\": [\"/api/v1/\", \"/api/v2/\"],"
echo "     \"path_exact\": false"
echo "   }"

echo ""
echo "🎯 匹配规则："
echo "  📌 精确匹配 (path_exact: true):"
echo "    - 请求路径必须完全等于前缀"
echo "    - 例如: /api/v1/ 只匹配 /api/v1/，不匹配 /api/v1/users"
echo ""
echo "  📌 前缀匹配 (path_exact: false):"
echo "    - 请求路径必须以指定前缀开头"
echo "    - 例如: /api/v1/ 匹配 /api/v1/users、/api/v1/data 等"

echo ""
echo "🔄 处理流程："
echo "  1. 请求到达 → 检查域名匹配"
echo "  2. 检查路径前缀匹配"
echo "  3. 如果匹配 → 走负载均衡转发到上游服务器"
echo "  4. 如果不匹配 → 继续其他处理逻辑（静态文件/PHP处理）"
echo ""
echo "📋 PHP站点混合处理："
echo "  ✅ /api/users → 负载均衡转发到API服务器"
echo "  ✅ /admin/login → 负载均衡转发到管理服务器"  
echo "  ✅ /index.php → 本地PHP FastCGI处理"
echo "  ✅ /static/style.css → 本地静态文件服务"

echo ""
echo "📊 测试用例："
echo "  配置: path_prefixes=[\"/api/v1/\", \"/admin/\"], path_exact=false"
echo ""
echo "  ✅ 匹配的路径:"
echo "    - /api/v1/users"
echo "    - /api/v1/data"
echo "    - /admin/login"
echo "    - /admin/dashboard"
echo ""
echo "  ❌ 不匹配的路径:"
echo "    - /api/v2/users"
echo "    - /public/index.html"
echo "    - /static/css/style.css"
echo "    - /"

echo ""
echo "🚀 使用方法："
echo "  1. 在管理面板中配置路径前缀"
echo "  2. 设置匹配模式（精确/前缀）"
echo "  3. 配置后端服务器"
echo "  4. 启用负载均衡"
echo "  5. 测试请求转发"

echo ""
echo "💡 最佳实践："
echo "  - API路径使用前缀匹配: /api/v1/, /api/v2/"
echo "  - 管理路径使用精确匹配: /admin"
echo "  - 静态资源不配置前缀，直接本地服务"
echo "  - 动态内容配置前缀，走负载均衡"

echo ""
echo "✅ 路径前缀匹配功能已实现！"
