#!/bin/bash

# 测试威胁情报功能
echo "🛡️ 测试威胁情报功能"
echo "================================"

echo "📊 新增的免费威胁情报源："
echo "  ✅ Spamhaus DROP - 垃圾邮件IP列表"
echo "  ✅ Spamhaus EDROP - 扩展垃圾邮件IP列表"
echo "  ✅ OpenPhish - 钓鱼网站列表"
echo "  ✅ PhishTank - 钓鱼网站数据库"
echo "  ✅ Blocklist.de - 德国威胁情报"
echo "  ✅ DShield - SANS威胁情报"
echo "  ✅ Tor Exit Nodes - Tor出口节点"
echo "  ✅ Malware Bazaar - 恶意软件哈希"
echo "  ✅ URLhaus - 恶意URL列表"
echo "  ✅ Feodo Tracker - 僵尸网络IP"

echo ""
echo "🗄️ SQLite数据库功能："
echo "  ✅ 持久化存储IOC数据"
echo "  ✅ 自动数据清理（30天过期）"
echo "  ✅ 威胁统计和分析"
echo "  ✅ 更新日志记录"
echo "  ✅ 内存缓存 + 数据库存储"

echo ""
echo "🔄 更新频率："
echo "  - 每30分钟检查一次更新"
echo "  - 各数据源独立更新频率"
echo "  - 自动错误重试机制"

echo ""
echo "📁 数据存储位置："
echo "  - 数据库: ./data/threat_intel.db"
echo "  - 日志文件: ./data/threat_intel.log"
echo "  - 自动轮转和清理"

echo ""
echo "🚀 使用方法："
echo "  1. 重启SSLcat服务"
echo "  2. 查看日志确认威胁情报源启动"
echo "  3. 监控数据库文件大小"
echo "  4. 检查威胁检测效果"

echo ""
echo "📈 预期效果："
echo "  - 更全面的威胁检测覆盖"
echo "  - 持久化的威胁情报数据"
echo "  - 减少误报和漏报"
echo "  - 更好的安全防护能力"

echo ""
echo "🔍 监控命令："
echo "  # 查看数据库大小"
echo "  ls -lh ./data/threat_intel.db"
echo ""
echo "  # 查看威胁情报日志"
echo "  tail -f ./data/threat_intel.log"
echo ""
echo "  # 查看数据库内容（需要sqlite3）"
echo "  sqlite3 ./data/threat_intel.db 'SELECT COUNT(*) FROM iocs;'"
